### ISSUE TITLE
Application unexpectedly quit

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/StudioTVPlayer#26]
Faulting application name: StudioTVPlayer.exe, version: 0.8.8982.22386, time stamp: 0x66af5745
Faulting module name: avutil-58.dll, version: 58.2.100.0, time stamp: 0x63fd8e65
Exception code: 0xc0000005
Fault offset: 0x0000000000015ad5
Faulting process id: 0x0x8DC
Faulting application start time: 0x0x1DB0DD9A01399E1
Faulting application path: C:\StudioTVPlayer\StudioTVPlayer.exe
Faulting module path: C:\StudioTVPlayer\avutil-58.dll
Report Id: f4e5d072-9f60-4963-a2c4-de0559719e83
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sfahadshahzad** [comment]
Hi,

Just downloaded the file and trying to run application but it will automatically quit.

Regards,
Fahad

**Comment by jaskie** [comment]
Please, check out and provide a log with call stack - both from Windows
Application log and from log folder, if possible.

wt., 24 wrz 2024 o 15:02 sfahadshahzad ***@***.***>
napisał(a):

**Comment by jaskie** [comment]
Hi,
maybe you have previous configuration that points to some directory where some file causes the fault?
The StudioTVPlayer configuration is in %ProgramData%\StudioTVPlayer (e.g. C:\ProgramData\StudioTVPlayer if you have Windows on C: drive). Maybe delete the configuration first.
Anyway, having such file to fix the crash would be great.
There will be no logs, except call stack in Windows logs, I was wrong in previous message (deleted). Look for .NET Runtime errors in Windows Application log, it also would be useful.
Kind regards,
Jerzy

**Comment by sfahadshahzad** [comment]
Hi,

The issue resolved when I delete the configuration from %ProgramData%\StudioTVPlayer.

Regards,
Fahad
