### ISSUE TITLE
Player stopped

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/StudioTVPlayer#4]
Hi,

Just tried the new player application and noticed below issues do far.

* The player application stopped when modifying settings while clip is loaded and playing.
* There are multiple time application automatically quit

Regards,

Fahad

**Comment by jaskie** [comment]
Hi Fahad,
please provide some more info, how can I reproduce this? Any particular
settings.
BTW, thanks for testing
Kind regards,
Jurek

wt., 25 paź 2022 o 15:18 sfahadshahzad ***@***.***>
napisał(a):

**Comment by sfahadshahzad** [comment]
The FFMPEG Stream Out also getting error.
![FFMPEG OUT-1](https://user-images.githubusercontent.com/1608007/197787101-e746d48c-e203-463b-8245-ccb6f0a9d280.jpg)
![FFMPEG-OUT-2](https://user-images.githubusercontent.com/1608007/197787131-658c31cf-5a64-4e35-8b6e-f762a99335c4.jpg)

**Comment by jaskie** [comment]
Fahad, please, check it out now, and reopen if the same problems remains.

**Comment by sfahadshahzad** [comment]
Issue resolved.

**Comment by sfahadshahzad** [comment]
Hi,

The player is again stopped working when I try to play the clip that was played earlier,

![player stopped](https://user-images.githubusercontent.com/1608007/198044835-9e080fee-70c3-452d-be57-6aacdd3e0dc2.jpg)

**Comment by jaskie** [comment]
So this seems to be separate issue (other than the crashes). Please, try to find steps to reproduce the behavior, it will be much easier to find actual bug.
