### ISSUE TITLE
FFMPEG stream output

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/StudioTVPlayer#9]
Hi,

There is bug when adding more stream ffmpeg stream outputs currently only one working fine.

Kindly let me know how to add metadata for the stream output.

Regards,

Fahad

**Comment by jaskie** [comment]
Hi,
try to check newer release, and read the [first wiki](https://github.com/jaskie/StudioTVPlayer/wiki/FFmpeg-stream-output)
Regards, Jurek
